#
# (C) Copyright 2017 MicroSys Electronics GmbH
# (C) Copyright 2018 HIT
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y   := s32v234car.o

#########################################################################
